### ISSUE TITLE
Port to windows and add it to modmesh_viewer CI workflow

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#106]
This issue is opened to track the ongoing work of porting to windows.

**Comment by yungyuc** [comment]
@tychuang1211 is working on it.

**Comment by yanagiragi** [comment]
Will we have a CI specific for Windows build? or just compatible to Windows but CI stills runs on Linux workflow?

**Comment by yungyuc** [comment]
GitHub action has windows runner.  We do not need a separate CI system.

It would be ideal that both Linux and windows use the same workflow.  If that is too hard, using two workflows is acceptable.

**Comment by tychuang1211** [comment]
I'm trying to port modmesh on Windows. it works smoothly in Release mode but crashes when running linear_wave app in Debug mode. 
The problem is, PySide from PyPI has it's own copy of Qt DLLs, and will try to load them when being called.
It's not a problem in Release mode because if a DLL with the same module name is already loaded in memory, the system uses the loaded DLL.
![image](https://user-images.githubusercontent.com/33109379/185093292-4b099297-1b8e-4281-aec9-b6d20eb0b2e4.png)
In Debug mode however, as shown in the picture, it loads QtCored.dll instead (which is QtCore.dll with debugging symbols). And then QtCore.dll is loaded from PySide directory, causing our problem
What I am trying to do is to build PySide6 from source so it use existing Qt DLLs,
![image](https://user-images.githubusercontent.com/33109379/185094153-1792df96-6f8a-49a3-bd12-2e64cf4d4127.png)
though according to [README.md](https://github.com/pyside/pyside-setup#building-additional-options) of pyside-setup it seems that there will be copies anyway, since there is no proper rpath support on Windows.
