### ISSUE TITLE
The way of finding PUI needs to be improved

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/solvcon#280]
The way of finding PUI in [`modmesh/view.py`](https://github.com/solvcon/modmesh/blob/master/modmesh/view.py#L67) is using hard-code import path, which is not a good approach.
This is a point that needs improvement.

**Comment by yungyuc** [comment]
@j8xixo12 It is more robust to use the permalink to refer to the code: https://github.com/solvcon/modmesh/blob/d92add6ee4f07caca20b52c943dd57b672e89a5a/modmesh/view.py#L67

**Comment by yungyuc** [comment]
This is to follow up https://github.com/solvcon/modmesh/pull/271#discussion_r1510178905

**Comment by j8xixo12** [comment]
> @j8xixo12 It is more robust to use the permalink to refer to the code:
> 
> https://github.com/solvcon/modmesh/blob/d92add6ee4f07caca20b52c943dd57b672e89a5a/modmesh/view.py#L67

Thanks, I will use permalink in the future.

**Comment by yungyuc** [comment]
We should check for progress on 8th June

**Comment by j8xixo12** [comment]
@yungyuc I have an idea about how to find PUI (or other python library) and  would like to discuss with you!

I think we can create a python script to manage third-party library in `thirdparty` folder. Considering `modmesh` may have both c++ and python third party library in the future,I think the folder structure could looks like this:
```
thirdparty/
├── c++
│   └── some_c++_lib
└── python
    └── py_lib_management.py
    └── PUI
    └── xxx 
```

I assume the c++ libraries have `CMakeLists.txt` so we don't need to worry about how to import them, but python needs.
We also can control which python library need to be import in `py_lib_management.py` based on the toggle system.

However, considering that we mmight need to package `modmesh` as a standalone executable in the future, I'm not sure if this design is a good approach.

**Comment by yungyuc** [comment]
> ```
> thirdparty/
> ├── c++
> │   └── some_c++_lib
> └── python
>     └── py_lib_management.py
>     └── PUI
>     └── xxx 
> ```

This is good.  The directory name should not use a non-letter character `+`, so we should name it like `cpp`.  But other than that it looks feasible.

In the beginning, since we do not have a lot of (2+) thirdparty packages, maybe they can be still flat under `thirdparty/`, and the management script may be simpler.

Building and deploying `modmesh` as a binary will need a lot of work like https://github.com/orgs/solvcon/projects/7, and [once the GUI gets cleaned up, we will start to ... assemble it back with solvcon](https://github.com/solvcon/modmesh/discussions/336).  The deployment requires a lot of work.  We may need to augment https://github.com/solvcon/devenv to power it in the future.

Do you think this is clear enough for you to start to make the script for managing PUI?

**Comment by j8xixo12** [comment]
Yes, it is clear enough for me to start to write the script for managing PUI!

**Comment by yungyuc** [comment]
@j8xixo12 is prototyping in #364

**Comment by yungyuc** [comment]
@j8xixo12 Is there anything needing to be done after #364 (excluding #378)?

**Comment by j8xixo12** [comment]
I think there is nothing more to be done.

**Comment by yungyuc** [comment]
Close for everything is done
