### ISSUE TITLE
Alignment verification for both `ConcreteBuffer` and `BufferExpander`

### ISSUE THREAD

**Issue by tigercosmos** [solvcon/solvcon#307]
Ensure alignment verification for both `ConcreteBuffer` and `BufferExpander`. Upon casting the raw buffer to typed data, it is imperative to validate if the alignment meets the required alignment. This alignment validation should be implemented without utilizing a template and must be enforced within the buffer's allocator.

Original discussion from https://github.com/solvcon/modmesh/pull/304#discussion_r1555105483

**Comment by tigercosmos** [comment]
@yungyuc  I think for a while, I cannot think of a case in the memory that could be not in alignment. Currently, `SimpleCollector` holds a `BufferExpander`, and `SimpleCollector` never exchanges the expander with another `SimpleCollector` in another type. 

For example, `SimpleCollector<int>` will not exchange the underlying expander with the one of `SimpleCollector<double>`. 

In addition, a `SimpleCollector` will never expand the buffer with a different alignment of the buffer. Therefore, I wonder if this issue is still valid. Do you have any thoughts on this?

**Comment by yungyuc** [comment]
When implementing `BufferExpander`, I planned to align the memory at allocation.  It calls an abstraction layer for multi-platform code.  On mac the alignment allocation is unnecessary because [`malloc()` is always aligned](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/malloc.3.html).

The alignment may be a thing for GPU.  But I agree we do not need to do anything about it because we do not even have a GPU CI runner.

If you do not think alignment is a thing, we can close this issue for now.  Let me do it.
