### ISSUE TITLE
Review the missing Q_OBJECT macros

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#85]
I didn't include the `Q_OBJECT` macro in `QObject` sub-classes (the `R`-named classes).  It is simply an overlook.

Before the macro is added to the `QObject` sub-classes, we should make sure we know how to correctly add it.  This issue is filed to keep track of the fix.

**Comment by yanagiragi** [comment]
Please let me have a try.

**Comment by yanagiragi** [comment]
The `Q_Object` is required if you use the singal/slot mechanism.

In Qt, there are two ways to connect the event with the callback: string based and functor based connections. The string based is done by using per-processer to replace the macros in the code, while the functor based has nothing special than a regular function in C++. The biggest difference between the two approaches is the functor based allows implicit type conversion and checks type in compile time.

For more info you may check [the official document](https://doc.qt.io/qt-6/signalsandslots-syntaxes.html) for comparison details.

The string based connections defines some macros (`slots`, `signals`, `Q_OBJECT`, `SLOT`, `SIGNAL`) to achieve (partial) type checks in compile time.

In short, here's how it works:

```cpp
class someClass : QObject
{
     Q_OBJECT // Required macro

     signals:
          signalSendVoid(void);
          slgnalSendInteger(int);

     slots: // slot is the callback that receives the event emited from `signals`
          slotReceiveVoid(void);
          slotReceiveInteger(int);
}

// main code starts here
auto sc = someClass ();

// connect the `sc.signalSendVoid` event to `sc:.lotReceiveVoid`
connect(sc, SIGNAL(signalSendVoid(void)), sc, SLOT(slotReceiveVoid(void))

// connect the `sc.slgnalSendInteger` event to `sc.slgnalSendInteger`,
// the argument `sc.slgnalSendInteger` received is passed from `sc.slgnalSendInteger`
connect(sc, SIGNAL(slgnalSendInteger(int)), sc, SLOT(slgnalSendInteger(int))

// but how does the int argument comes from?
// The argument mostly comes from QT UI components, for example a slider component 
// will have a signal that pass a float representing the current value of the slider

// And, for custom events, one may use `emit slgnalSendInteger(1)` to raise a event in code

````

The above pseudo codes is only a brief intro to the slot/signal mechanism, for more details, I recommend to have a look to below articles:

[為什麼 Qt 要有 Signals/Slots](https://marco79423.net/articles/%E7%82%BA%E4%BB%80%E9%BA%BC-qt-%E8%A6%81%E6%9C%89-signalsslots)

[Signal與Slot](https://edliwomun.gitbooks.io/qt-cpp-cross-platform-application-development/content/Qt-Basic-Usage-and-Function/Qt-Signal-and-Slot.html)

In my opinion, since the `connect` method already supports functor, it seems there is no cons to use the string based connection except it disallows explicit type conversion.

---

Also, I've created a simple prototype to demo the same functionality with two approaches in `yanagiragi/85-review-qobject`:

![圖片](https://user-images.githubusercontent.com/7404517/180631840-964753c8-8b46-417b-9812-812a545a098b.png)

The new added buttons increment the counts of itself every time it got pressed.

The implementation details are in [RPythonText.hpp](https://github.com/yanagiragi/modmesh/blob/85-review-qobject/cpp/modmesh/view/RPythonText.hpp) and [RPythonText.cpp](https://github.com/yanagiragi/modmesh/blob/85-review-qobject/cpp/modmesh/view/RPythonText.cpp)

**Comment by yungyuc** [comment]
Is it correct that if we go with the functor connection, the signal and slot will work without adding `Q_OBJECT` macro to our `R*` classes?

**Comment by yanagiragi** [comment]
yes. In fact in [here](https://github.com/solvcon/modmesh/blob/master/cpp/modmesh/view/RPythonText.cpp#L54) `QPushButton::clicked` is already a signal.

As long as we don't use `SLOT` and `SIGNAL` macro we won't need `Q_OBJECT` macro.

**Comment by yungyuc** [comment]
I see.  So the lack of `Q_OBJECT` in the `R*` classes is not a serious problem for now.  Perhaps we can close the issue and revisit this in the future if we find `SLOT` and `SIGNAL` macros are necessary.  What do you think @yanagiragi ?

**Comment by yanagiragi** [comment]
Sure. Let's close it.
